version: '3.9'
services:
  bot:
    build: ./Bot
    container_name: Bot
    restart: on-failure
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    volumes:
      - ./Bot:/Bot
    env_file:
      - .env
